=== NeilCFord/Fate-XSLT/atomic-robo.dtd
<?xml version='1.0' encoding='utf-8' ?>
<!ELEMENT character (id, current-fate-points, experience-points, aspects, skills, stress?, stunts, consequences?, hacks?, experiences?, notes?)>

  <!ELEMENT id (charname, playername, affiliation)>
    <!ELEMENT charname (#PCDATA)>
    <!ATTLIST charname nickname CDATA #IMPLIED>
    <!ELEMENT playername (#PCDATA)>
    <!ELEMENT affiliation (#PCDATA)>

    <!ELEMENT current-fate-points (#PCDATA)>
    <!ELEMENT experience-points (#PCDATA)>

    <!ELEMENT aspects (aspect*)>
      <!ELEMENT aspect (#PCDATA)>
      <!ATTLIST aspect type (concept|mode|omega) #REQUIRED>
      <!ATTLIST aspect mode_name CDATA           #IMPLIED>

    <!ELEMENT skills (mode*, skill*)>
      <!ELEMENT mode (skill*)>
      <!ATTLIST mode name   CDATA #REQUIRED>
      <!ATTLIST mode rating CDATA #REQUIRED>
      <!ELEMENT skill (#PCDATA)>
      <!ATTLIST skill name   CDATA #REQUIRED>
      <!ATTLIST skill rating CDATA #IMPLIED>
      <!ATTLIST skill add    CDATA #IMPLIED>

    <!ELEMENT stress (#PCDATA)>
      <!--
        If we use Skill Modes, it gets very difficult to calculate stress boxes.
        It might be MVP to just declare the box count in the XML & be done w/it.
      -->
      <!ATTLIST stress physical CDATA #REQUIRED>
      <!ATTLIST stress mental   CDATA #REQUIRED>

    <!ELEMENT stunts (stunt*)>
      <!ELEMENT stunt (#PCDATA)>
      <!ATTLIST stunt name CDATA #IMPLIED>

    <!ELEMENT consequences (consequence*)>
      <!ELEMENT consequence (#PCDATA)>
        <!ATTLIST consequence effect CDATA #IMPLIED>
        <!ATTLIST consequence severity (mild|moderate|severe|mild-physical|mild-mental) #REQUIRED>

    <!ELEMENT hacks (#PCDATA)>
      <!ATTLIST hacks conditions  (true|false) #IMPLIED> <!-- Fate System Toolkit     -->
      <!ATTLIST hacks corruption  (true|false) #IMPLIED> <!-- Fate Freeport Companion -->
      <!ATTLIST hacks skill-modes (true|false) #IMPLIED> <!-- Fate System Toolkit     -->

    <!ELEMENT experiences (experience*)>
      <!ELEMENT experience (#PCDATA)>

    <!ELEMENT notes (#PCDATA)>

=== NeilCFord/Fate-XSLT/characters/TesladyneSF/heather_dorsey.xml
<?xml version = '1.0'?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE atomic-robo SYSTEM "../../atomic-robo.dtd">
<character>
 <id>
  <charname>Heather Dorsey</charname>
  <playername>Jennifer Cornish</playername>
  <affiliation>Tesladyne's SF office</affiliation>
  <description>
    TBD<!--
         I suggested to Jenn that Heather might've gone to the
         Institute for Social Ecology
    -->
  </description>
 </id>
 <current-fate-points>3</current-fate-points>
 <experience-points>0</experience-points>
 <aspects>
  <aspect type="Concept">"Black Widow for Greenpeace"?</aspect>
  <aspect type="Mode" mode-name="Science">TBD</aspect>
  <aspect type="Mode" mode-name="Intrigue">TBD</aspect>
  <aspect type="Mode" mode-name="Action">TBD</aspect>
  <aspect type="Omega">TBD</aspect>
 </aspects>
 <skills>
  <mode rating="3" name="Science" stress-type="mental">
   <skill name="Notice"/>
   <skill name="Will"/>
   <skill name="(all other Sciences)"/>
  </mode>
  <mode rating="2" name="Intrigue" stress-type="physical">
   <skill name="Athletics"/>
   <skill name="Burglary"/>
   <skill name="Contacts"/>
   <skill name="Deceive"/>
   <skill name="Notice"/>
   <skill name="Stealth"/>
  </mode>
  <mode rating="1" name="Action">
   <skill name="Athletics"/>
   <skill name="Combat"/>
   <skill name="Notice"/>
   <skill name="Physique"/>
   <skill name="Provoke"/>
   <skill name="Vehicles"/>
  </mode>
 </skills>
 <stunts>
 </stunts>
 <consequences>
 </consequences>
 <experiences>
  <experience/>
  <experience/>
  <experience/>
 </experiences>
 <notes>
  Regardless of what modes you have, if they're all standard modes you get ONE of the following improvements:
  * Specialize one trained skill.
  * Focus one trained skill and specialize one focused skill.
  * Focus three trained skills.

  If one of your modes is Science, however, choose ONE improvement from the Everyone list,
  and also apply ALL of the following improvements:
  * Specialize one trained skill.
  * Focus one trained skill.
  * Specialize one focused skill.

  Probably increase Ecology, Biology within Science
 </notes>
</character>

=== NeilCFord/Fate-XSLT/characters/TesladyneSF/dennis_kim.xml
<?xml version = '1.0'?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE atomic-robo SYSTEM "../../atomic-robo.dtd">
<character>
 <id>
  <charname>Dennis Kim</charname>
  <playername>Supporting NPC</playername>
  <affiliation>Tesladyne SF (Resident Scientist)</affiliation>
  <description>
    22-year old, scruffy, Phish T-shirt, acoustic guitar
    http://bigbangtheory.wikia.com/wiki/Dennis_Kim
  </description>
 </id>
 <current-fate-points>3</current-fate-points>
 <experience-points>0</experience-points>
 <aspects>
  <aspect type="Concept">Brilliant Stoner Resident Scientist</aspect>
  <aspect type="Mode" mode-name="Science">Literally Plays 11-Dimensional Chess</aspect>
  <aspect type="Mode" mode-name="Banter">Abrasive Boy Genius Who Mellowed Out (Mostly)</aspect>
  <aspect type="Mode" mode-name="Intrigue">Smuggled My Grandfather Out of North Korea</aspect>
  <aspect type="Omega">Youngest Recipient of the Stevenson Award</aspect>
 </aspects>
 <skills>
  <mode rating="3" name="Science" stress-type="mental">
   <skill name="Higher-Dimensional Math" add="2"/>
   <skill name="Notice"/>
   <skill name="Pharmacology" add="0"/>
   <skill name="Theoretical Physics" add="2"/>
   <skill name="Will"/>
   <skill name="(all other Sciences)"/>
  </mode>
  <mode rating="2" name="Banter" stress-type="mental">
   <skill name="Contacts"/>
   <skill name="Deceive" add="0"/>
   <skill name="Empathy"/>
   <skill name="Notice"/>
   <skill name="Provoke" add="1"/>
   <skill name="Rapport"/>
   <skill name="Will"/>
  </mode>
  <mode rating="1" name="Intrigue">
   <skill name="Athletics"/>
   <skill name="Burglary" add="0"/>
   <skill name="Contacts"/>
   <skill name="Deceive"/>
   <skill name="Notice"/>
   <skill name="Stealth"/>
  </mode>
 </skills>
 <stunts>
 </stunts>
 <consequences>
 </consequences>
 <experiences>
  <experience/>
  <experience/>
  <experience/>
 </experiences>
 <notes/>
</character>

=== NeilCFord/Fate-XSLT/characters/TesladyneSF/karen_alazar.xml
<?xml version = '1.0'?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE atomic-robo SYSTEM "../AtomicRobo/atomic-robo.dtd">
<character>
 <id>
  <charname>Karen Alazar</charname>
  <playername>Supporting NPC</playername>
  <affiliation>Tesladyne SF (Action Scientist)</affiliation>
  <description>
    A stocky woman born in Los Angeles to Eritrean immigrant parents.
    Went to Cal for Engineering, currently lives in Oakland.
    Could easily pass for a Forgotten Realms Gold Dwarf, both in appearance and culture.
  </description>
 </id>
 <current-fate-points>3</current-fate-points>
 <experience-points>0</experience-points>
 <aspects>
  <aspect type="Concept">TBD</aspect>
  <aspect type="Mode" mode-name="Science">So Many Gadgets</aspect>
  <aspect type="Mode" mode-name="Soldier">USAF Veteran of Afghanistan and Iraq</aspect>
  <aspect type="Mode" mode-name="Action">"...and MY AXE."</aspect>
  <aspect type="Omega">TBD</aspect>
 </aspects>
 <skills>
  <mode rating="3" name="Science" stress-type="mental"> <!-- ARRPG pg85 -->
   <skill name="Civil Engineering"      add="1"/> <!-- Focus 1 Trained from Science Mode -->
   <skill name="Communications Systems" add="2"/> <!-- Spec 1 Trained from Science Mode -->
   <skill name="Notice"/>
   <skill name="Will"/>
   <skill name="(all other Sciences)"/>
  </mode>
  <mode rating="2" name="Soldier" stress-type="physical"> <!-- ARRPG pg91 -->
   <skill name="Athletics"/>
   <skill name="Combat"/>
   <skill name="Contacts"/>
   <skill name="Notice"/>
   <skill name="Physique"/>
   <skill name="Tactics"/>
   <skill name="Vehicles" add="1"/> <!-- Spec 1 Focused from Science Mode -->
   <skill name="Will"/>
  </mode>
  <mode rating="1" name="Action"> <!-- ARRPG pg82 -->
   <skill name="Athletics"/>
   <skill name="Combat"/>
   <skill name="Notice"/>
   <skill name="Physique"/>
   <skill name="Provoke"/>
   <skill name="Vehicles"/>
  </mode>
 </skills>
 <stunts>
  <stunt name=" ">TBD</stunt>
  <stunt name=" ">TBD</stunt>
  <stunt name=" ">TBD</stunt>
  <stunt name=" ">TBD</stunt>
  <stunt name=" ">TBD</stunt>
 </stunts>
 <consequences>
 </consequences>
 <experiences>
  <experience/>
  <experience/>
  <experience/>
 </experiences>
 <notes>
  http://en.wikipedia.org/wiki/Habesha_name
  http://en.wikipedia.org/wiki/Category:Eritrean_culture
 </notes>
</character>

=== NeilCFord/Fate-XSLT/characters/AtomicRobo/nikola_tesla.xml
<?xml version = '1.0'?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE atomic-robo SYSTEM "atomic-robo.dtd">
<character>
 <id>
  <charname>Nikola Tesla</charname>
  <playername>sample Atomic Robo character</playername>
  <affiliation>Westinghouse Electric</affiliation>
 </id>
 <current-fate-points>2</current-fate-points>
 <experience-points>0</experience-points>
 <aspects>
  <aspect type="Concept">Eccentric Inventor of Beautiful Apparatuses</aspect>
  <aspect type="Mode" mode-name="Science">Master of Lightning*</aspect>
  <aspect type="Mode" mode-name="Banter">Magnetic Charm</aspect>
  <aspect type="Mode" mode-name="Action"/>
  <aspect type="Omega">My Method Is Different</aspect>
 </aspects>
 <skills>
  <mode rating="3" name="Science" stress-type="mental">
   <skill name="Electrical Engineering" add="2"/>
   <skill name="Mechanical Engineering" add="2"/>
   <skill name="Physics" add="2"/>
   <skill name="Will"    add="1"/>
   <skill name="Notice"  add="1"/>
   <skill name="(All other Sciences)"/>
  </mode>
  <mode rating="2" name="Banter" stress-type="mental">
   <skill name="Contacts" add="1"/>
   <skill name="Deceit"/>
   <skill name="Empathy"/>
   <skill name="Provoke"  add="1"/>
   <skill name="Rapport"/>
   <skill name="Will"/>
  </mode>
  <mode rating="1" name="Action">
   <skill name="Athletics" add="2"/>
   <skill name="Combat"    add="1"/>
   <skill name="Physique"/>
   <skill name="Vehicles"/>
  </mode>
 </skills>
 <stunts>
  <stunt name="Signature Aspect">
    Master of Lightning (invoke once for free, compel at two fate points instead of one)
  </stunt>
 </stunts>
 <consequences>
  <consequence severity="Mild">mild one</consequence>
 </consequences>
 <experiences>
  <experience>experience1: this is longer than the others</experience>
  <experience>experience2</experience>
  <experience used="true">experience3</experience>
 </experiences>
</character>

=== NeilCFord/Fate-XSLT/characters/nikola_tesla.xml
<?xml version = '1.0'?>
<?xml-stylesheet type="text/xsl" href="../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE atomic-robo SYSTEM "../atomic-robo.dtd">
<character>
 <id>
  <charname>Nikola Tesla</charname>
  <playername>sample Atomic Robo character</playername>
  <affiliation>Westinghouse Electric</affiliation>
 </id>
 <refresh>2</refresh>
 <current-fate-points>2</current-fate-points>
 <aspects>
  <aspect type="concept">Eccentric Inventor of Beautiful Apparatuses</aspect>
  <aspect type="science_mode">Master of Lightning*</aspect>
  <aspect type="banter_mode">Magnetic Charm</aspect>
  <aspect type="action_mode"/>
  <aspect type="omega">My Method Is Different</aspect>
 </aspects>
 <skills>
  <mode rating="3" name="Science">
   <skill name="Electrical Engineering" add="2"/>
   <skill name="Mechanical Engineering" add="2"/>
   <skill name="Physics" add="2"/>
   <skill name="Will"    add="1"/>
   <skill name="Notice"  add="1"/>
   <skill name="(All other Sciences)"/>
  </mode>
  <mode rating="2" name="Banter">
   <skill name="Contacts" add="1"/>
   <skill name="Deceit"/>
   <skill name="Empathy"/>
   <skill name="Provoke"  add="1"/>
   <skill name="Rapport"/>
   <skill name="Will"/>
  </mode>
  <mode rating="1" name="Action">
   <skill name="Athletics" add="2"/>
   <skill name="Combat"    add="1"/>
   <skill name="Physique"/>
   <skill name="Vehicles"/>
  </mode>
 </skills>
 <stunts>
  <stunt name="Signature Aspect">
    Master of Lightning (invoke once for free, compel at two fate points instead of one)
  </stunt>
 </stunts>
 <hacks skill-modes="true"/>
 <consequences>
  <consequence severity="mild">mild one</consequence>
 </consequences>
</character>

=== NeilCFord/Fate-XSLT/characters/TesladyneSF/frank_rogers.xml
<?xml version = '1.0'?>
<?xml-stylesheet type="text/xsl" href="../../xslt/atomic-robo_html.xsl"?>
<!DOCTYPE atomic-robo SYSTEM "../AtomicRobo/atomic-robo.dtd">
<character>
 <id>
  <charname>Frank Rogers</charname>
  <playername>Michael Wood</playername>
  <affiliation>Tesladyne SF (Action Scientist PC)</affiliation>
  <description>
    TBD
  </description>
 </id>
 <current-fate-points>3</current-fate-points>
 <experience-points>0</experience-points>
 <aspects>
  <aspect type="Concept">TBD</aspect>
  <aspect type="Mode" mode-name="Telepath">TBD</aspect>
  <aspect type="Mode" mode-name="Martial Artist">TBD</aspect>
  <aspect type="Mode" mode-name="Action">The Batman of Human Resources</aspect>
  <aspect type="Omega">TBD</aspect>
 </aspects>
 <skills>
  <mode rating="3" name="Telepath" stress-type="mental"> <!-- ARRPG pg92 -->
   <skill name="Deceive"/>
   <skill name="Empathy"/>
   <!-- OR Focus 1 Trained Skill instead of Hallucinations -->
   <skill name="Hallucinations"/>
   <skill name="Provoke"/>
   <skill name="Rapport"/>
   <skill name="Will"/>
  </mode>
  <mode rating="2" name="Martial Artist" stress-type="physical"> <!-- ARRPG pg88 -->
   <skill name="Athletics"/>
   <skill name="Combat"/>
   <skill name="Notice"/>
   <skill name="Physique"/>
   <skill name="Stealth"/>
   <skill name="Will"/>
  </mode>
  <mode rating="1" name="Action">
   <skill name="Athletics"/>
   <skill name="Combat"/>
   <skill name="Notice"/>
   <skill name="Physique"/>
   <skill name="Provoke"/>
   <skill name="Vehicles"/>
  </mode>
 </skills>
 <stunts>
  <stunt name=" ">TBD</stunt>
  <stunt name=" ">TBD</stunt>
  <stunt name=" ">TBD</stunt>
  <stunt name=" ">TBD</stunt>
  <stunt name=" ">TBD</stunt>
 </stunts>
 <consequences>
 </consequences>
 <experiences>
  <experience/>
  <experience/>
  <experience/>
 </experiences>
 <notes/>
</character>
