=== NeilCFord/Fate-XSLT/fcs.dtd
<?xml version='1.0' encoding='utf-8' ?>
<!ELEMENT fcs (id, refresh, current-fate-points, aspects, skills, extras, stunts, consequences?)>

<!ELEMENT id (charname, playername, description)>
	<!ELEMENT charname (#PCDATA)>
  <!ELEMENT playername (#PCDATA)>
		<!ATTLIST charname nickname CDATA #IMPLIED>
	<!ELEMENT description (#PCDATA)>

	<!ELEMENT refresh (#PCDATA)>
	<!ELEMENT current-fate-points (#PCDATA)>

  <!ELEMENT aspects (aspect*)>
		<!ELEMENT aspect (#PCDATA)>
		<!ATTLIST aspect type (high_concept|trouble) #IMPLIED>

	<!ELEMENT skills (skill*)>
    <!ELEMENT skill (#PCDATA)>
		<!ATTLIST skill name   CDATA #REQUIRED>
		<!ATTLIST skill rating CDATA #REQUIRED>

	<!ELEMENT extras (extra*)>
    <!ELEMENT extra (#PCDATA)>

  <!ELEMENT stunts (stunt*)>
		<!ELEMENT stunt (#PCDATA)>
<!--
     TODO: Think about stunt att name, with the base text being the effect, instead
-->
      <!ATTLIST stunt effect CDATA #IMPLIED>

	<!ELEMENT consequences (consequence*)>
		<!ELEMENT consequence (#PCDATA)>
      <!ATTLIST consequence effect CDATA #IMPLIED>
      <!ATTLIST consequence severity (mild|moderate|severe|mild-physical|mild-mental) #REQUIRED>

=== NeilCFord/Fate-XSLT/characters/zird_the_arcane.xml
<?xml version = '1.0'?>
<?xml-stylesheet type="text/xsl" href="../xslt/fcs_html.xsl"?>
<!DOCTYPE fate-core SYSTEM "../fcs.dtd">
<fcs>
  <id>
    <charname>Zird the Arcane</charname>
    <playername>sample FATE Core character</playername>
    <description>A sharp-featured scholar with a dark triangular beard.</description>
  </id>
  <refresh>2</refresh>
  <current-fate-points>2</current-fate-points>
  <aspects>
    <aspect type="high_concept">Wizard for Hire</aspect>
    <aspect type="trouble">Rivals in the Collegia Arcana</aspect>
    <aspect>If I Haven't Been There, I've Read About It</aspect>
    <aspect>Not The Face!</aspect>
    <aspect>Doesn't Suffer Fools Gladly</aspect>
  </aspects>
  <skills>
    <skill rating="4" name="Lore"/>
    <skill rating="3" name="Rapport"/>
    <skill rating="3" name="Crafts"/>
    <skill rating="2" name="Athletics"/>
    <skill rating="2" name="Will"/>
    <skill rating="2" name="Investigate"/>
    <skill rating="1" name="Fight"/>
    <skill rating="1" name="Resources"/>
    <skill rating="1" name="Contacts"/>
    <skill rating="1" name="Notice"/>
  </skills>
  <extras>
    <extra>Collegia Arcana Mage</extra>
  </extras>
  <stunts>
    <stunt effect="Can make Physical Recovery attempts w/Lore">Scholar, Healer</stunt>
  </stunts>
  <consequences>
    <consequence severity="mild">mild one</consequence>
  </consequences>
</fcs>
