=== NeilCFord/Fate-XSLT/sotc.dtd
<?xml version='1.0' encoding='utf-8' ?>
<!ELEMENT character (id, refresh, current-fate-points, aspects, skills, stunts, gadgets, consequences?, phases)>

  <!ELEMENT id (charname, concept, playername, archetype)>
    <!ELEMENT charname (#PCDATA)>
    <!ELEMENT concept  (#PCDATA)>
    <!ELEMENT playername (#PCDATA)>
      <!ATTLIST charname nickname CDATA #IMPLIED>
    <!ELEMENT archetype (#PCDATA)>

    <!ELEMENT refresh (#PCDATA)>
    <!ELEMENT current-fate-points (#PCDATA)>

    <!ELEMENT aspects (aspect*)>
      <!ELEMENT aspect (#PCDATA)>

    <!ELEMENT skills (skill*)>
      <!ELEMENT skill (#PCDATA)>
      <!ATTLIST skill name   CDATA #REQUIRED>
      <!ATTLIST skill page   CDATA #REQUIRED>
      <!ATTLIST skill rating CDATA #REQUIRED>

    <!ELEMENT stunts (stunt*)>
      <!ELEMENT stunt (#PCDATA)>
      <!ATTLIST stunt effect CDATA #IMPLIED>
      <!ATTLIST stunt page   CDATA #REQUIRED>
      <!ATTLIST stunt skill  CDATA #REQUIRED>
<!--
     TODO: Think about stunt att name, with the base text being the effect, instead
-->

    <!ELEMENT gadgets (gadget*)>
      <!ELEMENT gadget (#PCDATA)>
      <!ATTLIST gadget page    CDATA #REQUIRED>
      <!ATTLIST gadget upgrade CDATA #REQUIRED>

    <!ELEMENT consequences (consequence*)>
      <!ELEMENT consequence (#PCDATA)>
        <!ATTLIST consequence effect CDATA #IMPLIED>
        <!ATTLIST consequence severity (mild|moderate|severe) #REQUIRED>

    <!ELEMENT phases (background, the-great-war, your-novel, phase4, phase5)>
      <!ELEMENT background (events*, aspect1, aspect2)>
        <!ELEMENT events  (#PCDATA)>
        <!ELEMENT aspect1 (#PCDATA)>
        <!ELEMENT aspect2 (#PCDATA)>
      <!ELEMENT the-great-war (century-club-patron, events*, aspect1, aspect2)>
        <!ELEMENT century-club-patron (#PCDATA)>
      <!ELEMENT your-novel (guest-stars, events*, aspect1, aspect2)>
        <!ATTLIST your-novel title CDATA #IMPLIED>
        <!ELEMENT guest-stars (#PCDATA)>
      <!ELEMENT phase4 (events*, aspect1, aspect2)>
        <!ATTLIST phase4 title CDATA #IMPLIED>
      <!ELEMENT phase5 (events*, aspect1, aspect2)>
        <!ATTLIST phase5 title CDATA #IMPLIED>

=== NeilCFord/Fate-XSLT/characters/jet_black.xml
<?xml version = '1.0'?>
<?xml-stylesheet type="text/xsl" href="../xslt/sotc_html.xsl"?>
<!DOCTYPE spirit-of-the-century SYSTEM "../sotc.dtd">
<character>
 <id>
  <charname>Jet Black</charname>
  <concept>Gadget Guy</concept>
  <playername>sample SotC character</playername>
  <archetype>Spirit Centurion</archetype>
 </id>
 <refresh>10</refresh>
 <current-fate-points>10</current-fate-points>
 <aspects>
  <aspect>Motorhead</aspect>
  <aspect>Unspoken Love (Sally)</aspect>
  <aspect>others</aspect>
 </aspects>
 <skills>
  <skill page="xx" rating="5" name="Athletics"/>
  <skill page="xx" rating="4" name="Engineering"/>
  <skill page="xx" rating="3" name="Guns"/>
  <skill page="xx" rating="3" name="Pilot"/>
  <skill page="xx" rating="3" name="Stealth"/>
  <skill page="xx" rating="3" name="Fists"/>
  <skill page="xx" rating="2" name="Drive"/>
  <skill page="xx" rating="2" name="Endurance"/>
  <skill page="xx" rating="2" name="Resolve"/>
  <skill page="xx" rating="2" name="Intimidation"/>
  <skill page="xx" rating="1" name="Alertness"/>
  <skill page="xx" rating="1" name="Science"/>
  <skill page="xx" rating="1" name="Might"/>
  <skill page="xx" rating="1" name="Rapport"/>
  <skill page="xx" rating="1" name="Weapons"/>
 </skills>
 <stunts>
  <stunt effect="blah" page="xx" skill="Engineering">The Amazing Jet Pack (Personal Gadget)</stunt>
 </stunts>
 <gadgets>
  <gadget page="xx" upgrade="xx">The Amazing Jet Pack</gadget>
 </gadgets>
 <consequences>
  <consequence severity="mild">mild one</consequence>
 </consequences>
 <phases>
  <background>
    <events>blah</events>
    <aspect1>blah</aspect1>
    <aspect2>blah</aspect2>
  </background>
  <the-great-war>
    <century-club-patron>blah</century-club-patron>
    <events>blah</events>
    <aspect1>blah</aspect1>
    <aspect2>blah</aspect2>
  </the-great-war>
  <your-novel title="Proper Noun and the Pulp Adventure!">
    <guest-stars/>
    <events>blah</events>
    <aspect1>blah</aspect1>
    <aspect2>blah</aspect2>
  </your-novel>
  <phase4 title="x">
    <events>blah</events>
    <aspect1>blah</aspect1>
    <aspect2>blah</aspect2>
  </phase4>
  <phase5 title="x">
    <events>blah</events>
    <aspect1>blah</aspect1>
    <aspect2>blah</aspect2>
  </phase5>
 </phases>
</character>
